resourcePacks:
  Default:
    url: https://mediafilez.forgecdn.net/files/4572/162/VanillaDefault+1.20.zip
    permission: resourcepackselector.pack.default
#  Custom1:
#    url: https://yourdirectdownload.link/custom1.zip
#    permission: resourcepackselector.pack.custom1

Settings:
  promptAtJoin: true

cooldown:
  enabled: true
  duration: 300 # Cooldown duration in seconds
